name: Fabrication Mobile NEXUS Gratuit
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Recuperation du code NEXUS
        uses: actions/checkout@v4
      - name: Preparation du paquet universel
        run: |
          mkdir build_output
          cp app.py build_output/
          cp app.json build_output/
          echo "✨ NEXUS est pret pour le déploiement gratuit."
      - name: Creation du lien de telechargement
        uses: actions/upload-artifact@v4
        with:
          name: NEXUS-Application-Package
          path: build_output/
